
export const API_ENDPOINTS = {

  ATTACHMENTS: "attachments",
  ANALYTICS: "analytics",
  ATTRIBUTES: "attributes",
  ATTRIBUTE_VALUES: "attribute-values",
  ORDER_STATUS: "order_status",
  ORDERS: "orders",
  USERS: "users",
  REGISTER: "register",
  PRODUCTS: "products",
  PRODUCT_STATUS_UPDATE:"status-product",
  POPULAR_PRODUCTS: "popular-products",
  COUPONS: "coupons",
  UTILITY_PAYMENT:"utility-payment",
  SMS_LOG:"sms-log",
  CUSTOMERS: "customers",
  TAXES: "taxes",
  SHIPPINGS: "shipping",
  SETTINGS: "settings",
  CATEGORIES: "categories",
  SHOP_CATEGORIES: "shop-categories",

  FIND_BY_DATE_RANGE: "find-by-date-range",
  

  SELECT_SHOP_CATEGORIES:"select-shop-categories",
  TAGS: "tags",
  PARENT_CATEGORIES: "fetch-parent-category",
  OFFER: "offers",
  BRAND_OFFERS: "brand-offers",
  FETCH_SHOP_CATEGORIES:"fetch-shop-category",
  TYPES: "types",
  PROFILE_UPDATE: "profile-update",
  LOGOUT: "logout",
  ME: "me",
  TOKEN: "token",
  BLOCK_USER: "users/ban-user",
  UNBLOCK_USER: "users/active-user",
  CHANGE_PASSWORD: "Change Password",
  FORGET_PASSWORD: "forget-password",
  VERIFY_FORGET_PASSWORD_TOKEN: "verify-forget-password-token",
  RESET_PASSWORD: "reset-password",
  DOWNLOAD_INVOICE: "download/invoice",
  APPROVE_SHOP: "approve-shop",
  DISAPPROVE_SHOP: "disapprove-shop",
  SHOP_DELIVERY_STATUS: "shop-delivery-status",
  SHOPS: "all-shop",
  ADMIN_SHOP:"admin-shop",
  MY_SHOPS: "my-shops",
  WITHDRAWS: "withdraws",
  APPROVE_WITHDRAW: "approve-withdraw",
  APPROVE_INVOICE_UPLOAD: "approve-invoice-upload",
  STAFFS: "staffs",
  ADD_STAFF: "users/add-staff",
  MASTER_PRODUCT: "master-products",
  PRODUCT_OFFERS:"product-offers",
  PRODUCT_BRAND_OFFERS:"product-brand-offers",
  PAGINATION_MASTER_PRODUCT: "pagination-master-products",
  STORE_MASTER_PRODUCT: "store-master-product",
  CREATED_MASTER_PRODUCT:"created-master-products",
  MASTER_PRODUCT_STATUS_UPDATE:"status-master-product",
  PRODUCT_COMMISSSION:"products-commission",
  SHOP_COMMISSION:"shop-commission",
  SHOP_COMMISSION_TYPE:"shop-commission-type",
  UPDATE_REFERRAL_COMMISSION:"update-referral-commission",
  GET_REFERRAL_COMMISSION:"get-referral-commission",
  USER_VERIFY:"user-verify",
  RESEND_CODE:"resend-code",
  IMPORT_PRODUCTS: "import-products/",
  IMPORT_ALL_PRODUCTS: "import-all-products/",
  IMPORT_ATTRIBUTES: "import-attributes/",
  IMPORT_VARIATION_OPTIONS: "import-variation-options/",
  IMPORT_ALL_VARIATION_OPTIONS: "import-all-variation-options/",
  IMPORT_MASTER_VARIATION_OPTIONS: "import-master-variation-options/",
  IMPORT_MASTER_PRODUCTS: "import-master-products/",
  IMPORT_SHOPS: "import-shops/",

  LOGS:"logs",
  SHOP_VISITORS: 'shop-visitors',
  SIGNUP_OFFER: "signup-offer",
  STORE_LICENSES:"stored-licenses",
  STORE_LICENSE_ATTACHMENT:"store-license-attachment",
  ALL_TAXES:"all-taxes",
  INVOICES_REWARD: 'invoices-reward',
  BILL: 'bill',
  BILL_REWARD: 'bill-reward',
  APPROVE_BILL: "approve-bill",
  ADMIN_DELIVERY:'admin/delivery',
  DELIVERY:'delivery',
  APPROVE_DELIVERY: "approve-delivery",
  SHOP_DELIVERY_CONFIG: "shop-delivery-config",
  DELIVERY_COST:"delivery-cost",
  VERIFY_CHECKOUT: "checkout/verify",

  CONTACT: '/contact',

  GET_WALLET_COMMISSION:"get-wallet-commission",
  GET_USER_WALLET_DETAILS:"get-user-wallet-details",

  GET_USER_REFERRAL_NETWORK : 'get-user-referral-network',
  

  QUESTIONS: "questions",
  REVIEWS: "reviews",
  ABUSIVE_REPORTS_DECLINE: "abusive_reports/reject",
  ABUSIVE_REPORTS: "abusive_reports",

  WHATSAPP_CAMPAIGN:'webhook',

  TERM_LIFE_INSURANCE: 'term-life-insurance',

  QUIZ:'quiz',

  ADD_AUTH_RETAILERS: 'add-auth-brands',
  GET_AUTH_BRANDS: 'auth-brands',
  UPDATE_AUTH_BRANDS: 'update-auth-brands',

  RETAILER_BRANDS:'retailer-brands',

  COURSES: 'courses', 
  EXAMS: 'exams',
  EXAM_QUESTIONS: 'exam-questions',
  EXAM_QUESTIONS_SEARCH: 'exam-question-search',

  PAGINATED_EXAM_QUESTIONS: 'paginated-exam-questions',
  EXAM_SECTION: 'exam-sections',
  QUESTION_TYPE: 'question-type',

  MARKING_SCHEMES: 'marking-schemes',
  QUESTION_OPTIONS : 'question-options',

  EXAM_STUDENTS : 'exam_students',
  EXAM_ATTEMPTS: 'exam-attempts',
  EXAM_ATTEMPT_ANSWERS :'exam-attempt-answers',
  COURSES_WITH_EXAM_ATTEMPTS:'courses-with-exams-attempts',

  USER_EXAM_ATTEMTPS : 'user-exam-attempts',

  CLASS: '/class',
  CLASS_STREAMS: '/class-streams',

  BATCH : '/batch',
  BOOK : '/book',
  STUDY_MATERIAL: '/study-material',
  STUDENTS_LIST: '/students-list'
};

